Repository wunder3605/iri, pull requests merged in 2019-05, with the labels that each got.

#347 [fix #346] upgrade python module 'six' in travis-ci
  .travis.yml
Labels: DevOps (运维), bug（修复问题）

#344 Cherry pick v0.1.13
  .travis.yml
  scripts/iota_api/app.py
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: duplicate（重复）

#350 [fix #265] Define two functions for ancestor forwarding
  src/main/java/com/iota/iri/storage/PersistenceProvider.java
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/ZmqPublishProvider.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/main/java/com/iota/iri/storage/neo4j/Neo4jPersistenceProvider.java
  src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java
  src/test/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProviderTest.java
Labels: Performance（性能提升）

#349 [fix #348]modify vue_interface_test mock
  scripts/front_end/server/vue/vue_interface_test.go
Labels: bug（修复问题）

#355 [fix #354]format the code using gofmt
  scripts/front_end/server/main.go
  scripts/front_end/server/vue/vue_interface.go
  scripts/front_end/server/vue/vue_interface_test.go
Labels: Performance（性能提升）

#357 [fix #354] gofmt vue_interface_test.go
  scripts/front_end/server/vue/vue_interface_test.go
Labels: Format(格式)

#321 [fix #265]Ancestor forward
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/service/tipselection/impl/KatzCentralityTest.java
Labels: Performance（性能提升）

#353 [fix #352]1.add DevOPS page;2.DevOps url can be configed
  scripts/front_end/web/src/common/config/config.js
  scripts/front_end/web/src/routes.js
  scripts/front_end/web/src/views/nav1/DevOps.vue
Labels: New Feature(新功能)

#360 [fix #309] optimize network - add three new DatagramPackets and format files
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/network/UDPReceiver.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSinkPool.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSourceProcessor.java
Labels: Performance（性能提升）
