Repository wunder3605/iri, pull requests merged in 2019-02, with the labels that each got.

#109 [fix #108] Slow DAG sync to TM
  scripts/iota_api/chronic_txn_sync.py
  scripts/iota_cache/iota_cache.py
  scripts/iota_cache/iota_cache_test.py
Labels: bug

#111 [fix #110] SYNC hotfix
  scripts/iota_api/chronic_txn_sync.py
  scripts/iota_api/tag_generator.py
Labels: bug

#102 [fix #38] Conflux tip selection algorithm
  scripts/iota_cache/iota_cache.py
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/TipSelConfig.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatz.java
  src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorConflux.java
  src/main/java/com/iota/iri/storage/PersistenceProvider.java
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/ZmqPublishProvider.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/main/java/com/iota/iri/storage/neo4j/Neo4jPersistenceProvider.java
  src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java
  src/main/java/com/iota/iri/utils/IotaUtils.java
Labels: enhancement

#105 [fix #46] remove ipfs.
  .travis.yml
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_api/conf
  scripts/iota_cache/iota_cache.py
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/DbConfig.java
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/pluggables/utxo/BatchTxns.java
  src/main/java/com/iota/iri/pluggables/utxo/Transaction.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/utils/Converter.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/utils/ConverterTest.java
  src/test/java/com/iota/iri/utils/IotaIOUtilsTest.java
Labels: bug, enhancement

#113 [fix #112] Integrate UTXO and Storage
  pom.xml
  scripts/iota_api/app.py
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/model/TransactionHash.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/pluggables/utxo/Transaction.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/utils/IotaIOUtilsTest.java
Labels: bug

#119 [fix #118] Add HCGraph application section
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/applications.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/methods.tex
Labels: enhancement

#121 [fix #118] Add TikTok in application section
  document/yellow_paper/StreamNet/algorithms/tik_tok.tex
  document/yellow_paper/StreamNet/sections/applications.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
Labels: bug

#120 [fix #116] add k8s deploy document
  document/iota_deploy/k8s-deploy-info.md
  document/yellow_paper/StreamNet/StreamNet.bib
Labels: enhancement

#124 [#123] Remove timestamp
  scripts/iota_api/app.py
Labels: bug

#122 [fix #118] add missing figures
  document/yellow_paper/StreamNet/figures/attestation.pdf
  document/yellow_paper/StreamNet/figures/edge_info.pdf
  document/yellow_paper/StreamNet/figures/ranking.pdf
  document/yellow_paper/StreamNet/figures/trias.pdf
Labels: bug

#126 update implementation from dev.
  .travis.yml
  pom.xml
  scripts/iota_api/app.py
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/model/TransactionHash.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/pluggables/utxo/Transaction.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/utils/IotaIOUtilsTest.java
Labels: enhancement

#130 [fix #129] Creating clusters through yaml files
  document/iota_deploy/k8s-create-cluster-yaml.md
Labels: enhancement

#128 [fix #127] Integrate UTXO plus Storage plus Conflux
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  scripts/iota_deploy/iota_deploy.py
  scripts/iota_deploy/iota_deploy_prod.py
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/pluggables/utxo/BatchTxns.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/Txn.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnIn.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnOut.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
Labels: bug

#136 [fix #135] add iota client dockerfile
  scripts/Dockerfile
Labels: enhancement

#134 Merge v0.1streamnet
  document/iota_deploy/k8s-deploy-info.md
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/algorithms/conflux_order.tex
  document/yellow_paper/StreamNet/algorithms/get_pivot.tex
  document/yellow_paper/StreamNet/algorithms/tik_tok.tex
  document/yellow_paper/StreamNet/figures/attestation.pdf
  document/yellow_paper/StreamNet/figures/edge_info.pdf
  document/yellow_paper/StreamNet/figures/ranking.pdf
  document/yellow_paper/StreamNet/figures/trias.pdf
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/applications.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/methods.tex
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  scripts/iota_deploy/iota_deploy.py
  scripts/iota_deploy/iota_deploy_prod.py
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/pluggables/utxo/BatchTxns.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/Txn.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnIn.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnOut.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
Labels: bug, duplicate

#143 [fix #142] Cherry pick storage changes
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java
  src/test/java/com/iota/iri/BundleValidatorTest.java
  src/test/java/com/iota/iri/MilestoneTrackerTest.java
  src/test/java/com/iota/iri/TransactionValidatorTest.java
  src/test/java/com/iota/iri/benchmarks/dbbenchmark/states/DbState.java
  src/test/java/com/iota/iri/controllers/BundleViewModelTest.java
  src/test/java/com/iota/iri/controllers/MilestoneViewModelTest.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightCalculatorTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightWithEdgeCalculatorTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/DoubleSpendTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/RatingOneTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/TailFinderImplTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/WalkerAlphaTest.java
  src/test/java/com/iota/iri/storage/TangleTest.java
  src/test/java/com/iota/iri/storage/localinmem/LocalInMemoryGraphProviderTest.java
  src/test/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProviderTest.java
Labels: bug, enhancement

#141 [fix #140] get pivotal hash return null within empty graph
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug

#149 [fix #146] add line number after class name in log info.
  src/main/resources/logback.xml
Labels: enhancement

#150 [fix #127] Conflux support batch UTXO transactions
  scripts/examples/parallel_put_txn_two_nodes.sh
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
Labels: bug

#144 [fix #136] modify dockerfile
  scripts/Dockerfile
  scripts/docker-entrypoint.sh
Labels: enhancement

#152 [fix #151] Restore UTXO when Bootstrapping
  pom.xml
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/Txn.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnIn.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
  src/test/java/com/iota/iri/utils/IotaIOUtilsTest.java
Labels: enhancement

#154 Update docker-entrypoint.sh
  scripts/Dockerfile
  scripts/docker-entrypoint.sh
Labels: enhancement

#155 add dockerfile volume and add pip pkg
  scripts/Dockerfile
  scripts/requirements.txt
Labels: enhancement

#159 Update k8s-create-cluster-yaml.md
  .travis.yml
  document/iota_deploy/k8s-create-cluster-yaml.md
Labels: duplicate

#166 [fix #138] Document for how to deploy streamnet and related services
  scripts/iota_api/app.py
  scripts/iota_api/conf
Labels: duplicate

#168 cherry pick app.py
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
Labels: duplicate

#167 cherry pick add line number after class name in log info. (#149)
  src/main/resources/logback.xml
Labels: duplicate

#169 Merge pull request #141 from wunder3605/pivotHash
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: duplicate

#137 [fix #131] Tee demo
  scripts/examples/conflux_dag.sh
  scripts/iota_api/app.py
  scripts/tee/CLI/CLI.go
  scripts/tee/CLI/CLI_test.go
  scripts/tee/CLI/config.yaml
  scripts/tee/main.go
  scripts/tee/pagerank/pagerank.go
  scripts/tee/prepare_test_data.py
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/NodeConfig.java
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/pluggables/tee/BatchTee.java
  src/main/java/com/iota/iri/pluggables/tee/TEE.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/dto/GetBlocksInPeriodResponse.java
Labels: enhancement

#172 cherry pick [fix #151] Restore UTXO when restarting
  pom.xml
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/Txn.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnIn.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
  src/test/java/com/iota/iri/utils/IotaIOUtilsTest.java
Labels: duplicate
