Repository wunder3605/iri, pull requests merged in 2019-01, with the labels that each got.

#68 [fix #67] fix bug: transaction batch
  scripts/iota_api/app.py
Labels: bug

#69 [fix #28] Neo4j only store graph relationships
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/DbConfig.java
  src/main/java/com/iota/iri/storage/neo4j/Neo4jPersistenceProvider.java
Labels: bug

#71 [fix #70] Fix scripts: make functions in iota_cache can be called in other directories.
  .gitignore
  scripts/iota_api/app.py
  scripts/iota_api/chronic_txn_sync.py
  scripts/iota_cache/__init__.py
Labels: bug

#74 [fix #73] Remove the graph logic from the Katz centrality code
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatz.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
Labels: bug

#82 [fix #80] DAG add UTXO for DDos protection(definition)
  src/main/java/com/iota/iri/pluggables/Transaction.java
  src/main/java/com/iota/iri/pluggables/TransactionData.java
  src/main/java/com/iota/iri/pluggables/TransactionIn.java
  src/main/java/com/iota/iri/pluggables/TransactionOut.java
Labels: enhancement

#84 [fix #83] Implement trytesToAscii
  src/main/java/com/iota/iri/utils/Converter.java
  src/test/java/com/iota/iri/utils/ConverterTest.java
Labels: bug, enhancement

#79 [fix #72] fix output of batch transactions in iota [WIP]
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/DbConfig.java
Labels: bug

#88 [fix #87] add streamnet yellow paper (english version)
  document/yellow_paper/StreamNet/IEEEtran.bst
  document/yellow_paper/StreamNet/IEEEtran.cls
  document/yellow_paper/StreamNet/README.md
  document/yellow_paper/StreamNet/StreamNet.aux
  document/yellow_paper/StreamNet/StreamNet.bbl
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.blg
  document/yellow_paper/StreamNet/StreamNet.log
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/StreamNet.tex
  document/yellow_paper/StreamNet/figures/alpha.png
  document/yellow_paper/StreamNet/figures/dagvis.png
  document/yellow_paper/StreamNet/figures/double_spend.png
  document/yellow_paper/StreamNet/figures/edge_info.png
  document/yellow_paper/StreamNet/figures/fast_txn.png
  document/yellow_paper/StreamNet/figures/full_confirmation.png
  document/yellow_paper/StreamNet/figures/genesis.png
  document/yellow_paper/StreamNet/figures/lazy_txn.png
  document/yellow_paper/StreamNet/figures/offline.png
  document/yellow_paper/StreamNet/figures/random_equal.png
  document/yellow_paper/StreamNet/figures/random_unequal.png
  document/yellow_paper/StreamNet/figures/screenshot015.png
  document/yellow_paper/StreamNet/figures/simple_sn.png
  document/yellow_paper/StreamNet/figures/simple_transfer.png
  document/yellow_paper/StreamNet/figures/slow_txn.png
  document/yellow_paper/StreamNet/figures/spc.png
  document/yellow_paper/StreamNet/figures/super_weight.png
  document/yellow_paper/StreamNet/figures/trias.png
  document/yellow_paper/StreamNet/figures/txn_fail.png
  document/yellow_paper/StreamNet/figures/txn_success.png
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/applications.tex
  document/yellow_paper/StreamNet/sections/experiments.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
  document/yellow_paper/StreamNet/sections/methods.tex
  document/yellow_paper/StreamNet/sections/problems.tex
Labels: enhancement

#91 [fix #72] add one value in Tangle to store batchTxnCount. --part 3
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/storage/Tangle.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/storage/TangleTest.java
Labels: bug

#93 [fix #76] Enable .travis CI for python scripts
  .travis.yml
  scripts/iota_api/__init__.py
  scripts/iota_cache/iota_cache.py
  scripts/iota_cache/iota_cache_test.py
Labels: bug

#95 [fix #94] Change document figure format from png to eps
  document/yellow_paper/StreamNet/StreamNet.aux
  document/yellow_paper/StreamNet/StreamNet.bbl
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.blg
  document/yellow_paper/StreamNet/StreamNet.log
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/StreamNet.tex
  document/yellow_paper/StreamNet/figures/fast_txn.TpX
  document/yellow_paper/StreamNet/figures/fast_txn.eps
  document/yellow_paper/StreamNet/figures/genesis.TpX
  document/yellow_paper/StreamNet/figures/genesis.eps
  document/yellow_paper/StreamNet/figures/lazy_txn.TpX
  document/yellow_paper/StreamNet/figures/lazy_txn.eps
  document/yellow_paper/StreamNet/figures/random_equal.TpX
  document/yellow_paper/StreamNet/figures/random_equal.eps
  document/yellow_paper/StreamNet/figures/random_unequal.TpX
  document/yellow_paper/StreamNet/figures/random_unequal.eps
  document/yellow_paper/StreamNet/figures/simple_sn.TpX
  document/yellow_paper/StreamNet/figures/simple_sn.eps
  document/yellow_paper/StreamNet/figures/simple_transfer.TpX
  document/yellow_paper/StreamNet/figures/simple_transfer.eps
  document/yellow_paper/StreamNet/figures/slow_txn.TpX
  document/yellow_paper/StreamNet/figures/slow_txn.eps
  document/yellow_paper/StreamNet/figures/txn_fail.TpX
  document/yellow_paper/StreamNet/figures/txn_fail.eps
  document/yellow_paper/StreamNet/figures/txn_success.TpX
  document/yellow_paper/StreamNet/figures/txn_success.eps
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
Labels: bug

#97 [fix #96]Modify ci script
  .travis.yml
  scripts/iota_cache/iota_cache.py
Labels: bug, enhancement

#100 [fix #86] modify the code of translation between trytes and text
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/utils/Converter.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/utils/ConverterTest.java
Labels: bug

#99 [fix #98] Add Inclusive/Prism related info for Yellow Paper
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/StreamNet.tex
  document/yellow_paper/StreamNet/algorithms/tip_sel.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
  document/yellow_paper/StreamNet/sections/methods.tex
Labels: bug

#90 [fix #66] Add conflux total order, todo getChild by pivot chain
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
  src/test/java/com/iota/iri/storage/localinmem/LocalInMemoryGraphProviderTest.java
Labels: enhancement

#104 [fix #103] Add UTXO implement
  pom.xml
  src/main/java/com/iota/iri/pluggables/Transaction.java
  src/main/java/com/iota/iri/pluggables/TransactionData.java
  src/main/java/com/iota/iri/pluggables/TransactionIn.java
  src/main/java/com/iota/iri/pluggables/TransactionOut.java
  src/main/java/com/iota/iri/pluggables/utxo/Transaction.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionIn.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionOut.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
Labels: enhancement
