Repository wunder3605/iri, pull requests merged in 2019-04, with the labels that each got.

#247 [fix #246] Optimize UTXO
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnIn.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
Labels: bug

#250 Cherry pick v0.1.5
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnIn.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
Labels: duplicate

#252 Cherry pick v0.1.6
  .travis.yml
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightMemCalculatorTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
  src/test/java/com/iota/iri/storage/localinmem/LocalInMemoryGraphProviderTest.java
Labels: duplicate

#255 [fix #254] Bug fixes for UTXO Graph based enhancement
  pom.xml
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug

#256 Cherry pick v0.1.7
  .gitignore
  README.md
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/StreamNet.tex
  document/yellow_paper/StreamNet/algorithms/conflux_order.tex
  document/yellow_paper/StreamNet/algorithms/get_diff.tex
  document/yellow_paper/StreamNet/algorithms/get_pivot.tex
  document/yellow_paper/StreamNet/algorithms/get_tik_tok.tex
  document/yellow_paper/StreamNet/algorithms/is_covered.tex
  document/yellow_paper/StreamNet/algorithms/main_loop.tex
  document/yellow_paper/StreamNet/algorithms/mcmc.tex
  document/yellow_paper/StreamNet/algorithms/update_score.tex
  document/yellow_paper/StreamNet/figures/architecture.pdf
  document/yellow_paper/StreamNet/figures/block_format.pdf
  document/yellow_paper/StreamNet/figures/cluster_set_up.pdf
  document/yellow_paper/StreamNet/figures/get_diff.pdf
  document/yellow_paper/StreamNet/figures/node.pdf
  document/yellow_paper/StreamNet/figures/simple_sn.pdf
  document/yellow_paper/StreamNet/figures/total_order.pdf
  document/yellow_paper/StreamNet/figures/utxo.pdf
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/experiments.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
  document/yellow_paper/StreamNet/sections/methods.tex
  scripts/examples/one_node/cli_conf
  scripts/examples/one_node/conflux_dag.sh
  scripts/examples/one_node/get_balance.sh
  scripts/examples/one_node/parallel_put_txn.sh
  scripts/examples/one_node/start_cli.sh
  scripts/examples/one_node_batch/cli_conf
  scripts/examples/one_node_batch/conflux_dag.sh
  scripts/examples/one_node_batch/get_balance.sh
  scripts/examples/one_node_batch/parallel_put_txn.sh
  scripts/examples/one_node_batch/start_cli.sh
  scripts/examples/two_nodes/cli_conf_two_nodes_1
  scripts/examples/two_nodes/cli_conf_two_nodes_2
  scripts/examples/two_nodes/conflux_dag_two_nodes.sh
  scripts/examples/two_nodes/get_balance_two_nodes.sh
  scripts/examples/two_nodes/parallel_put_txn_double_spend.sh
  scripts/examples/two_nodes/parallel_put_txn_two_nodes.sh
  scripts/examples/two_nodes/start_cli_two_nodes.sh
  scripts/examples/two_nodes_batch/cli_conf_two_nodes_1
  scripts/examples/two_nodes_batch/cli_conf_two_nodes_2
  scripts/examples/two_nodes_batch/conflux_dag_two_nodes.sh
  scripts/examples/two_nodes_batch/get_balance_two_nodes.sh
  scripts/examples/two_nodes_batch/parallel_put_txn_double_spend.sh
  scripts/examples/two_nodes_batch/parallel_put_txn_two_nodes.sh
  scripts/examples/two_nodes_batch/start_cli_two_nodes.sh
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  scripts/iota_deploy/add_neighbors_batch.py
Labels: duplicate

#257 Cherry pick v0.1.8
  pom.xml
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: duplicate

#260 [fix #259]modify ut for vue frontend interfaces
  scripts/front_end/server/main.go
  scripts/front_end/server/vue/vue_interface.go
  scripts/front_end/server/vue/vue_interface_test.go
Labels: enhancement

#236 [fix #224] caliper support
  document/caliper/Caliper.md
  document/caliper/img/fabric-reprot-1.4.jpg
  document/caliper/img/npm-list-fabric-ca-client.jpg
Labels: enhancement

#266 [fix #264] Finalize SC paper
  document/yellow_paper/StreamNet/ACM-Reference-Format.bst
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/StreamNet.tex
  document/yellow_paper/StreamNet/algorithms/get_pivot.tex
  document/yellow_paper/StreamNet/algorithms/main_loop.tex
  document/yellow_paper/StreamNet/figures/cluster_set_up.pdf
  document/yellow_paper/StreamNet/figures/multi_txn.pdf
  document/yellow_paper/StreamNet/figures/single_txn.pdf
  document/yellow_paper/StreamNet/sample-sigconf.tex
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/conclusion.tex
  document/yellow_paper/StreamNet/sections/experiments.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
  document/yellow_paper/StreamNet/sections/methods.tex
  scripts/iota_perf/data_analysis/data.csv
  scripts/iota_perf/data_analysis/data_analysis.R
  scripts/iota_perf/data_analysis/multiple.csv
  scripts/iota_perf/data_analysis/single.csv
Labels: bug

#263 [fix #267] add server deploy method
  scripts/Dockerfile
  scripts/examples/cluster/PerformanceTestDAG2TM_TPS.jmx
  scripts/examples/cluster/run.sh
  scripts/iota_deploy/server_deploy_batch.py
  scripts/iota_perf/data_generate.py
Labels: enhancement

#278 Cherry pick v0.1.10
  scripts/Dockerfile
  scripts/examples/cluster/PerformanceTestDAG2TM_TPS.jmx
  scripts/examples/cluster/run.sh
  scripts/iota_deploy/server_deploy_batch.py
  scripts/iota_perf/data_generate.py
Labels: duplicate

#276 [fix #271]optimize unit test
  scripts/front_end/server/vue/vue_interface_test.go
Labels: enhancement

#281 [fix #267] add readme and modify dockerfile
  scripts/Dockerfile
  scripts/docker-entrypoint.sh
  scripts/examples/cluster/README.md
  scripts/examples/cluster/run.sh
  scripts/examples/run_docker.sh
  scripts/iota_deploy/server_deploy_batch.py
Labels: DevOps (运维)

#280 [fix #279] optimize network
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/network/TCPNeighbor.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java
  src/main/java/com/iota/iri/service/API.java
Labels: Performance（性能提升）

#285 Cherry pick v0.1.11
  scripts/Dockerfile
  scripts/docker-entrypoint.sh
  scripts/examples/cluster/README.md
  scripts/examples/cluster/run.sh
  scripts/examples/run_docker.sh
  scripts/iota_deploy/server_deploy_batch.py
Labels: duplicate（重复）

#286 modify read link about deploy multiple nodes
  README.md
Labels: Document(文档)

#287 [fix #272] fix one doubleSpend problem
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/test/java/com/iota/iri/pluggables/utxo/UTXOGraphTest.java
Labels: bug（修复问题）

#289 [fix #288] Dag out of order
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug（修复问题）

#292 [fix #272] fix one doubleSpend problem (#287)
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/test/java/com/iota/iri/pluggables/utxo/UTXOGraphTest.java
Labels: bug（修复问题）, duplicate（重复）

#291 [fix #272] fix one doubleSpend problem (#287)
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/test/java/com/iota/iri/pluggables/utxo/UTXOGraphTest.java
Labels: duplicate（重复）

#293 [fix #288] Dag out of order (fix on fix)
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug（修复问题）, duplicate（重复）

#297 [fix 295] Get the host ip address through the dockerfile
  scripts/Dockerfile
  scripts/docker-entrypoint.sh
  scripts/examples/run_docker.sh
  scripts/iota_deploy/server_deploy_batch.py
Labels: DevOps (运维)

#299 [fix #288] Dag out of order (fix on fix)
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: duplicate（重复）

#300 [fix #288] Dag out of order (fix on fix)
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: duplicate（重复）

#294 change the branch of regression tests in v0.2-streamnet.
  .travis.yml
Labels: duplicate（重复）

#303 [fix 301] Add network and genesis forwarding
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/algorithms/gossip.tex
  document/yellow_paper/StreamNet/sample-sigconf.tex
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/methods.tex
Labels: Paper (论文)

#296 [fix #304] add option '-s' to curl command to silent the outputs.
  scripts/examples/one_node/parallel_put_txn.sh
  scripts/examples/one_node_batch/parallel_put_txn.sh
  scripts/examples/two_nodes/parallel_put_txn_double_spend.sh
  scripts/examples/two_nodes/parallel_put_txn_two_nodes.sh
  scripts/examples/two_nodes_batch/parallel_put_txn_double_spend.sh
  scripts/examples/two_nodes_batch/parallel_put_txn_two_nodes.sh
Labels: DevOps (运维)

#277 [fix #275] add three new endpoints
  scripts/examples/two_nodes_batch/get_balance_two_nodes.sh
  scripts/front_end/server/main.go
  scripts/front_end/server/vue/vue_interface.go
  scripts/front_end/server/vue/vue_interface_test.go
  scripts/front_end/web/config/index.js
  scripts/front_end/web/config/proxyConfig.js
  scripts/front_end/web/src/routes.js
  scripts/front_end/web/src/views/nav1/DagDB.vue
  scripts/front_end/web/src/views/nav1/LinkMap.vue
  scripts/front_end/web/src/views/nav1/ipConfig.js
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/dto/GetDAGResponse.java
  src/main/java/com/iota/iri/service/dto/GetTotalOrderResponse.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: New Feature(新功能)

#308 [fix #267] collect jmeter stress data
  scripts/examples/cluster/collect_stress_data.py
Labels: DevOps (运维)

#305 [fix #304]add option '-s' to curl command to silent the outputs. (#296)
  scripts/examples/one_node/parallel_put_txn.sh
  scripts/examples/one_node_batch/parallel_put_txn.sh
  scripts/examples/two_nodes/parallel_put_txn_double_spend.sh
  scripts/examples/two_nodes/parallel_put_txn_two_nodes.sh
  scripts/examples/two_nodes_batch/parallel_put_txn_double_spend.sh
  scripts/examples/two_nodes_batch/parallel_put_txn_two_nodes.sh
Labels: duplicate（重复）

#306 [fix #304] add option '-s' to curl command to silent the outputs. (#296)
  scripts/examples/one_node/parallel_put_txn.sh
  scripts/examples/one_node_batch/parallel_put_txn.sh
  scripts/examples/two_nodes/parallel_put_txn_double_spend.sh
  scripts/examples/two_nodes/parallel_put_txn_two_nodes.sh
  scripts/examples/two_nodes_batch/parallel_put_txn_double_spend.sh
  scripts/examples/two_nodes_batch/parallel_put_txn_two_nodes.sh
Labels: duplicate（重复）

#319 [fix #312]1.replace echart with webgraphviz;2.notice:should rum 'npm …
  scripts/front_end/web/package-lock.json
  scripts/front_end/web/package.json
  scripts/front_end/web/src/common/config/config.js
  scripts/front_end/web/src/main.js
  scripts/front_end/web/src/views/nav1/Approve.vue
  scripts/front_end/web/src/views/nav1/DagDB.vue
  scripts/front_end/web/src/views/nav1/Leviatom.vue
  scripts/front_end/web/src/views/nav1/StreamNet.vue
  src/main/java/com/iota/iri/service/API.java
Labels: bug（修复问题）

#314 [fix #267] add cluster deploy experiment script
  scripts/examples/cluster/run.sh
  scripts/examples/cluster/run_experiment.sh
  scripts/iota_deploy/add_neighbors_batch.py
  scripts/iota_deploy/server_deploy_batch.py
Labels: DevOps (运维)

#316 [fix #315] change regression-tests repo
  .travis.yml
Labels: DevOps (运维)

#320 [fix #267] devops code bug fix
  scripts/examples/cluster/run_experiment.sh
  scripts/iota_deploy/server_deploy_batch.py
Labels: bug（修复问题）

#323 [fix #322] 1.add netCoin page;2.upgrade element-ui;3.add scale function
  scripts/front_end/web/package-lock.json
  scripts/front_end/web/package.json
  scripts/front_end/web/src/main.js
  scripts/front_end/web/src/routes.js
  scripts/front_end/web/src/views/nav1/Leviatom.vue
  scripts/front_end/web/src/views/nav1/NetCoin.vue
  scripts/front_end/web/src/views/nav1/StreamNet.vue
Labels: New Feature(新功能)

#318 [fix #315] Change regression tests to triasteam v0.2
  .travis.yml
Labels: DevOps (运维), duplicate（重复）

#317 [fix #315] change regression-tests repo
  .travis.yml
Labels: DevOps (运维), bug（修复问题）, duplicate（重复）

#307 [fix #288] Dag out of order (more fix)
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/network/TransactionRequester.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
Labels: bug（修复问题）, duplicate（重复）

#327 [fix #311] don't request the trunk hash and branch hash of genesis transaction.
  src/main/java/com/iota/iri/validator/TransactionValidator.java
  src/test/java/com/iota/iri/TransactionValidatorTest.java
Labels: bug（修复问题）

#332 [fix #322] Add netCoinPage and modify request parameters(add request method)
  scripts/front_end/server/vue/vue_interface.go
  scripts/front_end/web/config/proxyConfig.js
  scripts/front_end/web/index.html
  scripts/front_end/web/src/common/config/config.js
  scripts/front_end/web/src/views/nav1/NetCoin.vue
  scripts/front_end/web/src/views/nav1/StreamNet.vue
  scripts/front_end/web/static/favicon.ico
Labels: bug（修复问题）

#331 [fix #330] Minor fixes for performance improvement
  scripts/iota_api/app.py
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug（修复问题）

#334 [fix #309] optimize network - add command parameter '--optimize-network' and rename the 'sendingPacket'
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/NetworkConfig.java
  src/main/java/com/iota/iri/network/Node.java
Labels: bug（修复问题）

#336 [fix #335] Compute score missing tip score
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
Labels: bug（修复问题）

#338 [fix #337]1.fix bug --- can't query node detail
  scripts/front_end/web/src/views/nav1/StreamNet.vue
Labels: bug（修复问题）

#329 Cherry pick v0.1.12
  .travis.yml
  README.md
  scripts/Dockerfile
  scripts/docker-entrypoint.sh
  scripts/examples/cluster/collect_stress_data.py
  scripts/examples/cluster/run.sh
  scripts/examples/cluster/run_experiment.sh
  scripts/examples/run_docker.sh
  scripts/examples/two_nodes_batch/get_balance_two_nodes.sh
  scripts/front_end/web/config/proxyConfig.js
  scripts/front_end/web/src/views/nav1/ipConfig.js
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  scripts/iota_deploy/add_neighbors_batch.py
  scripts/iota_deploy/server_deploy_batch.py
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/network/TCPNeighbor.java
  src/main/java/com/iota/iri/network/TransactionRequester.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java
  src/main/java/com/iota/iri/pluggables/tee/BatchTee.java
  src/main/java/com/iota/iri/pluggables/tee/TEE.java
  src/main/java/com/iota/iri/pluggables/tee/TEEFormatted.java
  src/main/java/com/iota/iri/pluggables/utxo/NodeFormatted.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/UTXOGraph.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/dto/GetDAGResponse.java
  src/main/java/com/iota/iri/service/dto/GetTotalOrderResponse.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightMemCalculatorTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
Labels: duplicate（重复）

#343 [fix #342]modify the noderank position in the vue
  scripts/front_end/server/vue/vue_interface.go
Labels: bug（修复问题）
