Repository wunder3605/iri, pull requests merged in 2019-03, with the labels that each got.

#175 [fix #127] Conflux support batch UTXO transactions
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
Labels: bug

#176 cherry pick tee demo from dev to stream1
  scripts/examples/conflux_dag.sh
  scripts/tee/CLI/CLI.go
  scripts/tee/CLI/CLI_test.go
  scripts/tee/CLI/config.yaml
  scripts/tee/main.go
  scripts/tee/pagerank/pagerank.go
  scripts/tee/prepare_test_data.py
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/NodeConfig.java
  src/main/java/com/iota/iri/pluggables/tee/BatchTee.java
  src/main/java/com/iota/iri/pluggables/tee/TEE.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/dto/GetBlocksInPeriodResponse.java
Labels: duplicate

#165 [fix #164] Add engineering document
  document/engineering_document/StreamNet_Engineering.diff
  document/engineering_document/StreamNet_Engineering.docx
  document/engineering_document/figures/StreamNet_Engineering/media/image1.jpg
Labels: enhancement

#184 Cherry pick v0.1
  Dockerfile
  README.md
  docker/entrypoint.sh
  document/engineering_document/StreamNet_Engineering.diff
  document/engineering_document/StreamNet_Engineering.docx
  document/engineering_document/figures/StreamNet_Engineering/media/image1.jpg
  scripts/Dockerfile
  scripts/examples/run_docker.sh
  scripts/iota_api/conf
  scripts/requirements.txt
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/service/API.java
Labels: duplicate

#181 modify StreamNet_Engineering document
  README.md
  document/engineering_document/StreamNet_Engineering.docx
Labels: enhancement

#185 [fix #146] Change log format
  src/main/resources/logback.xml
Labels: enhancement

#186 [fix #145] Catch ipfs error
  scripts/iota_api/app.py
Labels: bug

#194 [fix #92] save TxnCount in file.
  src/main/java/com/iota/iri/storage/PersistenceProvider.java
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/ZmqPublishProvider.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/main/java/com/iota/iri/storage/neo4j/Neo4jPersistenceProvider.java
  src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java
  src/test/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProviderTest.java
Labels: bug

#191 [fix #190] Performance improvement for conflux
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/TipSelConfig.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumWeightScoreTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
  src/test/java/com/iota/iri/storage/localinmem/LocalInMemoryGraphProviderTest.java
Labels: bug

#197 [fix #196] Get balance
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/service/API.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
Labels: enhancement

#200 [fix #181] add container startup method
  document/engineering_document/StreamNet_Engineering.docx
Labels: enhancement

#201 Cherry pick v0.1.2
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
  scripts/tee/Dockerfile
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/conf/BaseIotaConfig.java
  src/main/java/com/iota/iri/conf/TipSelConfig.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/PersistenceProvider.java
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/ZmqPublishProvider.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/main/java/com/iota/iri/storage/neo4j/Neo4jPersistenceProvider.java
  src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java
  src/test/java/com/iota/iri/BundleValidatorTest.java
  src/test/java/com/iota/iri/MilestoneTrackerTest.java
  src/test/java/com/iota/iri/TransactionValidatorTest.java
  src/test/java/com/iota/iri/benchmarks/dbbenchmark/states/DbState.java
  src/test/java/com/iota/iri/controllers/BundleViewModelTest.java
  src/test/java/com/iota/iri/controllers/MilestoneViewModelTest.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumWeightScoreTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightCalculatorTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightWithEdgeCalculatorTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/DoubleSpendTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/RatingOneTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/TailFinderImplTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/WalkerAlphaTest.java
  src/test/java/com/iota/iri/storage/TangleTest.java
  src/test/java/com/iota/iri/storage/localinmem/LocalInMemoryGraphProviderTest.java
  src/test/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProviderTest.java
Labels: duplicate

#203 [fix #202] fix hash error - different txs may produce the same hash.
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
Labels: bug

#205 [fix #204] remove milestone.
  .travis.yml
  src/main/java/com/iota/iri/service/API.java
Labels: enhancement

#208 [fix #207] TX transfer bug
  scripts/examples/cli_conf_two_nodes_1
  scripts/examples/cli_conf_two_nodes_2
  scripts/examples/conflux_dag_two_nodes.sh
  scripts/examples/parallel_put_txn_two_nodes.sh
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
Labels: bug

#206 [fix #209] fix dockerfile bug
  scripts/docker-entrypoint.sh
  scripts/iota_api/ipinfo.txt
  scripts/iota_api/modify_conf_file.py
Labels: bug

#220 Cherry pick v0.1.3
  .travis.yml
  document/engineering_document/StreamNet_Engineering.docx
  scripts/docker-entrypoint.sh
  scripts/examples/cli_conf_two_nodes_1
  scripts/examples/cli_conf_two_nodes_2
  scripts/examples/conflux_dag_two_nodes.sh
  scripts/examples/parallel_put_txn_two_nodes.sh
  scripts/iota_api/ipinfo.txt
  scripts/iota_api/modify_conf_file.py
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/utils/IotaIOUtils.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
Labels: duplicate

#213 [fix #212] get total order before get balance.
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/pluggables/utxo/Txn.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnIn.java
  src/main/java/com/iota/iri/pluggables/utxo/TxnOut.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
Labels: bug

#215 [fix #214] Formalize performance test
  scripts/iota_perf/Dockerfile
  scripts/iota_perf/PerformanceTestDAG2TM_TPS.jmx
  scripts/iota_perf/README.md
  scripts/iota_perf/data_generate.py
  scripts/iota_perf/nginx.conf
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest.java
Labels: bug

#229 [fix #228] add neighbors to an IRI node by app service
  scripts/iota_api/api.py
  scripts/iota_api/app.py
  scripts/iota_cache/iota_cache.py
Labels: enhancement

#221 [fix #218] Dag Web Service Interface
  scripts/front_end/server/README.md
  scripts/front_end/server/main.go
  scripts/front_end/server/vue/vue_interface.go
Labels: enhancement

#232 [fix #231] Add neighbor nodes based on different node topologies
  scripts/iota_deploy/add_neighbors_batch.py
Labels: enhancement

#238 [fix #237] SC paper improvement
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.tex
  document/yellow_paper/StreamNet/figures/single_txn.pdf
  document/yellow_paper/StreamNet/sections/experiments.tex
  scripts/iota_perf/data_analysis/data.csv
  scripts/iota_perf/data_analysis/data_analysis.R
Labels: bug

#235 [fix #231] Add a method for delete and query neighbor nodes
  scripts/iota_deploy/add_neighbors_batch.py
Labels: enhancement

#240 [fix #237] SC paper improvement
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/StreamNet.tex
  document/yellow_paper/StreamNet/figures/block_format.pdf
  document/yellow_paper/StreamNet/figures/cluster_set_up.pdf
  document/yellow_paper/StreamNet/sections/experiments.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
Labels: bug

#245 [fix #244] Mvn package error
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightMemCalculatorTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorKatzTest.java
  src/test/java/com/iota/iri/storage/localinmem/LocalInMemoryGraphProviderTest.java
Labels: bug
